//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fstCopy_Proj5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralListing
    {
        public int GeneralListingID { get; set; }
        public string Name { get; set; }
        public Nullable<int> NumberOfVotes { get; set; }
    }
}
